import SwiftUI

struct RecordedTranslatorModel {
    let translations: [TranslateLanguage] = [
        TranslateLanguage(france: "Bonjour! Il fait beau aujourd'hui.", italy: "Ciao! Oggi è una bella giornata.", germny: "Hallo! Heute ist ein schöner Tag.", uk: "Hello! It's a lovely day today.", russia: "Привет! Сегодня отличный день.", portugal: "Olá! Hoje está um lindo dia.", spain: "¡Hola! Hoy es un día hermoso."),
        TranslateLanguage(france: "Le vent me rappelle une vieille chanson.", italy: "Il vento mi ricorda una vecchia canzone.", germny: "Der Wind erinnert mich an ein altes Lied.", uk: "The wind reminds me of an old song.", russia: "Ветер напоминает мне старую песню.", portugal: "O vento me lembra uma velha canção.", spain: "El viento me recuerda una canción antigua."),
        TranslateLanguage(france: "Attention! Il y a un prédateur non loin.", italy: "Attenzione! C'è un predatore nei paraggi.", germny: "Vorsicht! Ein Raubtier ist in der Nähe.", uk: "Careful! There's a predator nearby.", russia: "Осторожно! Неподалёку хищник.", portugal: "Cuidado! Há um predador por perto.", spain: "¡Cuidado! Hay un depredador cerca."),
        TranslateLanguage(france: "J'aime jouer avec mes amis sur les branches.", italy: "Mi piace giocare con gli amici sui rami.", germny: "Ich spiele gern mit meinen Freunden auf den Zweigen.", uk: "I like playing with my friends on the branches.", russia: "Люблю играть с друзьями на ветках.", portugal: "Gosto de brincar com meus amigos nos galhos.", spain: "Me gusta jugar con mis amigos en las ramas."),
        TranslateLanguage(france: "Chante avec moi ma mélodie préférée.", italy: "Canta con me la mia melodia preferita.", germny: "Sing mit mir meine Lieblingsmelodie.", uk: "Sing with me my favorite melody.", russia: "Пой со мной мою любимую мелодию.", portugal: "Cante comigo minha melodia favorita.", spain: "Canta conmigo mi melodía favorita."),
        TranslateLanguage(france: "Il est temps de chercher de la nourriture.", italy: "È ora di cercare cibo.", germny: "Es ist Zeit, nach Essen zu suchen.", uk: "Time to look for food.", russia: "Время искать еду.", portugal: "É hora de procurar comida.", spain: "Es hora de buscar comida."),
        TranslateLanguage(france: "La journée a été merveilleuse, n'est-ce pas?", italy: "La giornata è stata bella, vero?", germny: "Der Tag war schön, nicht wahr?", uk: "The day has been great, hasn't it?", russia: "День удался, не правда ли?", portugal: "O dia foi maravilhoso, não é?", spain: "El día fue genial, ¿verdad?"),
        TranslateLanguage(france: "Pourquoi les humains aiment-ils me photographier?", italy: "Perché gli umani amano fotografarmi?", germny: "Warum fotografieren Menschen mich so gern?", uk: "Why do humans love to photograph me?", russia: "Почему люди любят меня фотографировать?", portugal: "Por que os humanos gostam de me fotografar?", spain: "¿Por qué a los humanos les gusta fotografiarme?"),
        TranslateLanguage(france: "J'aime voler haut dans les arbres.", italy: "Amo volare in alto sugli alberi.", germny: "Ich liebe es, hoch in den Bäumen zu fliegen.", uk: "I love flying high in the trees.", russia: "Люблю летать высоко над деревьями.", portugal: "Adoro voar alto nas árvores.", spain: "Me encanta volar alto entre los árboles."),
        TranslateLanguage(france: "La pluie commence, il faut chercher un abri.", italy: "Sta iniziando a piovere, cerco un riparo.", germny: "Es beginnt zu regnen, ich muss Schutz suchen.", uk: "The rain is starting, time to find shelter.", russia: "Начался дождь, пора искать укрытие.", portugal: "Está começando a chover, preciso de abrigo.", spain: "Está comenzando a llover, hay que buscar refugio."),
        TranslateLanguage(france: "L'hiver approche, il faut se préparer.", italy: "L'inverno sta arrivando, dobbiamo prepararci.", germny: "Der Winter naht, wir müssen uns vorbereiten.", uk: "Winter is coming, we must prepare.", russia: "Зима близко, нужно готовиться.", portugal: "O inverno está chegando, precisamos nos preparar.", spain: "Se acerca el invierno, hay que prepararse."),
        TranslateLanguage(france: "Ressens le rythme de mes ailes en vol.", italy: "Senti il ritmo delle mie ali in volo.", germny: "Fühle den Rhythmus meiner Flügel im Flug.", uk: "Feel the rhythm of my wings in flight.", russia: "Почувствуй ритм моих крыльев в полёте.", portugal: "Sinta o ritmo das minhas asas no voo.", spain: "Siente el ritmo de mis alas en vuelo."),
        TranslateLanguage(france: "Entends-tu comment j'appelle mes petits?", italy: "Senti come chiamo i miei piccoli?", germny: "Hörst du, wie ich meine Jungen rufe?", uk: "Do you hear how I call my chicks?", russia: "Слышишь, как я подзываю птенцов?", portugal: "Você ouve como chamo meus filhotes?", spain: "¿Oyes cómo llamo a mis polluelos?"),
        TranslateLanguage(france: "Chaque jour a sa propre chanson et humeur.", italy: "Ogni giorno ha la sua canzone e umore.", germny: "Jeder Tag hat sein eigenes Lied und seine Stimmung.", uk: "Every day has its own song and mood.", russia: "У каждого дня своя песня и настроение.", portugal: "Cada dia tem sua própria canção e humor.", spain: "Cada día tiene su propia canción y ánimo."),
        TranslateLanguage(france: "Les oiseaux chantent pour prévenir, pas seulement pour la beauté.", italy: "Gli uccelli cantano per avvertire, non solo per bellezza.", germny: "Vögel singen nicht nur zur Schönheit, sondern auch zur Warnung.", uk: "Birds sing not only for beauty but for warning.", russia: "Птицы поют не только для красоты, но и чтобы предупреждать.", portugal: "Os pássaros cantam não só pela beleza, mas para avisar.", spain: "Los pájaros cantan no sólo por belleza sino como advertencia."),
        TranslateLanguage(france: "Il y a beaucoup de nouveaux sons aujourd'hui.", italy: "Ci sono molti suoni nuovi oggi.", germny: "Heute gibt es viele neue Geräusche.", uk: "There are many new sounds today.", russia: "Сегодня много новых звуков вокруг.", portugal: "Há muitos sons novos hoje.", spain: "Hay muchos sonidos nuevos hoy."),
        TranslateLanguage(france: "Veux-tu connaître les secrets de la forêt?", italy: "Vuoi conoscere i segreti della foresta?", germny: "Willst du die Geheimnisse des Waldes wissen?", uk: "Do you want to know the secrets of the forest?", russia: "Хочешь узнать секреты леса?", portugal: "Você quer saber os segredos da floresta?", spain: "¿Quieres conocer los secretos del bosque?"),
        TranslateLanguage(france: "Le chant est ma manière de communiquer.", italy: "Il canto è il mio modo di comunicare.", germny: "Der Gesang ist meine Art zu kommunizieren.", uk: "The song is my way to communicate.", russia: "Песня – мой способ общения.", portugal: "O canto é meu modo de comunicar.", spain: "La canción es mi forma de comunicar."),
        TranslateLanguage(france: "Les sons de l'aube sont magiques.", italy: "I suoni dell'alba sono magici.", germny: "Die Klänge der Morgendämmerung sind magisch.", uk: "The sounds of dawn are magical.", russia: "Звуки рассвета самые волшебные.", portugal: "Os sons da alvorada são mágicos.", spain: "Los sonidos del amanecer son mágicos."),
        TranslateLanguage(france: "Merci d'écouter mon chant.", italy: "Grazie per ascoltare il mio canto.", germny: "Danke, dass du meinem Gesang zuhörst.", uk: "Thank you for listening to my song.", russia: "Спасибо, что слушаешь меня.", portugal: "Obrigado por ouvir meu canto.", spain: "Gracias por escuchar mi canto."),
        TranslateLanguage(france: "Mes ailes me portent vers des lieux sans souci.", italy: "Le mie ali mi portano in luoghi senza pensieri.", germny: "Meine Flügel tragen mich an sorglose Orte.", uk: "My wings carry me to carefree places.", russia: "Мои крылья уносят меня туда, где нет забот.", portugal: "Minhas asas me levam a lugares sem preocupações.", spain: "Mis alas me llevan a lugares sin preocupaciones."),
        TranslateLanguage(france: "La forêt est ma grande maison.", italy: "La foresta è la mia grande casa.", germny: "Der Wald ist mein großes Zuhause.", uk: "The forest is my big home.", russia: "Лес для меня большой дом.", portugal: "A floresta é minha grande casa.", spain: "El bosque es mi gran hogar."),
        TranslateLanguage(france: "Je chante même si peu m'écoutent.", italy: "Canto anche se pochi mi ascoltano.", germny: "Ich singe, auch wenn mich wenige hören.", uk: "I sing even if few listen.", russia: "Я пою, даже если меня мало слушают.", portugal: "Eu canto mesmo que poucos me ouçam.", spain: "Canto aunque pocos me escuchen."),
        TranslateLanguage(france: "Le vent m'emporte loin, mais je reviens.", italy: "Il vento mi porta lontano, ma torno.", germny: "Der Wind trägt mich weit, aber ich komme zurück.", uk: "The wind carries me far, but I return.", russia: "Ветер уносит меня далеко, но я возвращаюсь.", portugal: "O vento me leva longe, mas eu volto.", spain: "El viento me lleva lejos, pero vuelvo."),
        TranslateLanguage(france: "Le chant des oiseaux est l'aube pour l'âme.", italy: "Il canto degli uccelli è l'alba per l'anima.", germny: "Der Vogelgesang ist die Morgendämmerung für die Seele.", uk: "Bird singing is the dawn for the soul.", russia: "Пение птиц – рассвет для души.", portugal: "O canto dos pássaros é a aurora para a alma.", spain: "El canto de los pájaros es el amanecer para el alma."),
        TranslateLanguage(france: "Mon chant est plus fort quand je suis heureux(se).", italy: "Il mio canto è più forte quando sono felice.", germny: "Mein Gesang ist lauter, wenn ich glücklich bin.", uk: "My song is louder when I'm happy.", russia: "Моя песня громче, когда я счастлив(а).", portugal: "Meu canto é mais alto quando estou feliz.", spain: "Mi canción es más fuerte cuando estoy feliz."),
        TranslateLanguage(france: "Chaque trille raconte une histoire.", italy: "Ogni trillare racconta una storia.", germny: "Jedes Trillern erzählt eine Geschichte.", uk: "Every trill tells a story.", russia: "В каждом треле есть история.", portugal: "Cada trinado conta uma história.", spain: "Cada trino cuenta una historia."),
        TranslateLanguage(france: "Ne crains pas le silence, il prépare la nouvelle chanson.", italy: "Non temere il silenzio, prepara la nuova canzone.", germny: "Fürchte die Stille nicht, sie bereitet das neue Lied vor.", uk: "Don't fear the silence, it prepares new song.", russia: "Не бойся тишины, она готовит новую песню.", portugal: "Não temas o silêncio, ele prepara uma nova canção.", spain: "No temas el silencio, prepara una nueva canción."),
        TranslateLanguage(france: "Mes chants animent l'air du matin.", italy: "I miei canti animano l'aria del mattino.", germny: "Mein Gesang belebt die Morgenluft.", uk: "My songs enliven the morning air.", russia: "Мои песни оживляют утро.", portugal: "Minhas canções animam o ar da manhã.", spain: "Mis canciones animan el aire de la mañana."),
        TranslateLanguage(france: "Je chante pour attirer l'attention et trouver des amis.", italy: "Canto per attirare l'attenzione e trovare amici.", germny: "Ich singe, um Aufmerksamkeit zu erregen und Freunde zu finden.", uk: "I sing to attract attention and find friends.", russia: "Я пою, чтобы привлечь внимание и найти друзей.", portugal: "Eu canto para atrair atenção e encontrar amigos.", spain: "Canto para atraer atención y encontrar amigos."),
        TranslateLanguage(france: "L'heure change mon ton.", italy: "Il tempo cambia il mio tono.", germny: "Die Tageszeit ändert meinen Ton.", uk: "The time changes my tone.", russia: "Время суток меняет мой тон.", portugal: "O tempo muda meu tom.", spain: "El tiempo cambia mi tono."),
        TranslateLanguage(france: "Le chant me rend plus courageux(se).", italy: "Il canto mi rende più coraggioso(a).", germny: "Der Gesang macht mich mutiger.", uk: "Singing makes me braver.", russia: "Пение делает меня смелее.", portugal: "Cantar me torna mais corajoso.", spain: "Cantar me hace más valiente."),
        TranslateLanguage(france: "Mes petits apprennent à chanter avec moi.", italy: "I miei piccoli imparano a cantare con me.", germny: "Meine Jungen lernen mit mir zu singen.", uk: "My chicks learn to sing with me.", russia: "Птенцы учатся петь со мной.", portugal: "Meus filhotes aprendem a cantar comigo.", spain: "Mis polluelos aprenden a cantar conmigo."),
        TranslateLanguage(france: "Le chœur d'oiseaux est le plus bel orchestre.", italy: "Il coro di uccelli è la più bella orchestra.", germny: "Der Vogelsang ist das schönste Orchester.", uk: "The bird choir is the most beautiful orchestra.", russia: "Птичий хор – самый красивый оркестр.", portugal: "O coro de pássaros é a orquestra mais bela.", spain: "El coro de pájaros es la orquesta más hermosa."),
        TranslateLanguage(france: "Mon cœur bat au rythme de mes trilles.", italy: "Il mio cuore batte al ritmo dei miei trilli.", germny: "Mein Herz schlägt im Rhythmus meiner Triller.", uk: "My heart beats to the rhythm of my trills.", russia: "Моё сердце бьётся в такт моим трелям.", portugal: "Meu coração bate no ritmo dos meus trilos.", spain: "Mi corazón late al ritmo de mis trinos."),
        TranslateLanguage(france: "Parfois je chante pour moi, parfois pour toi.", italy: "A volte canto per me, a volte per te.", germny: "Manchmal singe ich für mich, manchmal für dich.", uk: "Sometimes I sing for myself, sometimes for you.", russia: "Иногда я пою для себя, иногда для тебя.", portugal: "Às vezes canto para mim, às vezes para você.", spain: "A veces canto para mí, a veces para ti."),
        TranslateLanguage(france: "Le chant aide à oublier les peurs.", italy: "Il canto aiuta a dimenticare le paure.", germny: "Der Gesang hilft, Ängste zu vergessen.", uk: "Singing helps to forget fears.", russia: "Пение помогает забыть страхи.", portugal: "Cantar ajuda a esquecer os medos.", spain: "Cantar ayuda a olvidar los miedos."),
        TranslateLanguage(france: "Chaque son est une goutte dans la mer de la vie.", italy: "Ogni suono è una goccia nel mare della vita.", germny: "Jeder Ton ist ein Tropfen im Meer des Lebens.", uk: "Every sound is a drop in the sea of life.", russia: "Каждый звук – капля в море жизни.", portugal: "Cada som é uma gota no mar da vida.", spain: "Cada sonido es una gota en el mar de la vida."),
        TranslateLanguage(france: "Les oiseaux connaissent les secrets du vent et du ciel.", italy: "Gli uccelli conoscono i segreti del vento e del cielo.", germny: "Vögel kennen die Geheimnisse von Wind und Himmel.", uk: "Birds know the secrets of wind and sky.", russia: "Птицы знают тайны ветра и неба.", portugal: "Os pássaros conhecem os segredos do vento e do céu.", spain: "Los pájaros conocen los secretos del viento y del cielo."),
        TranslateLanguage(france: "Je chanterai tant que j'aurai la force.", italy: "Canterò finché avrò forza.", germny: "Ich werde singen, solange ich Kraft habe.", uk: "I will sing as long as I have strength.", russia: "Обещаю петь, пока есть силы.", portugal: "Cantarei enquanto tiver forças.", spain: "Cantaré mientras tenga fuerzas."),
    ]

}


struct TranslateLanguage {
    var france: String
    var italy: String
    var germny: String
    var uk: String
    var russia: String
    var portugal: String
    var spain: String
}
